name: mindpath_dv
version: '1.0.0'
config-version: 2
profile: mindpath_dv

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  mindpath_dv:
    staging:
      +database: MINDPATH_ENT_DW
      +schema: STAGING
      +materialized: view
    raw_vault:
      +database: MINDPATH_ENT_DW
      +schema: RAW_VAULT
      +materialized: incremental
    business_vault:
      +database: MINDPATH_ENT_DW
      +schema: BUSINESS_VAULT
      +materialized: table

seeds:
  mindpath_dv:
    +database: MINDPATH_ENT_DW
    +schema: REFERENCE
    +quote_columns: false
