version: 2
models:
  - name: stg_clients
    columns:
      - name: client_id
        data_tests: [not_null]
      - name: hk_client
        data_tests: [not_null]
  - name: stg_referrals
    columns:
      - name: referral_id
        data_tests: [not_null]
      - name: hk_referral
        data_tests: [not_null]
  - name: stg_sessions
    columns:
      - name: session_id
        data_tests: [not_null]
      - name: hk_session
        data_tests: [not_null]
